# Generated by Django 4.1.5 on 2023-02-02 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('originator', models.CharField(max_length=100)),
                ('main_receiver', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='los/')),
                ('date_of_rec', models.DateField()),
                ('time_of_rec', models.TimeField()),
                ('datetime_of_action', models.DateTimeField(auto_now_add=True)),
                ('action_taken_by', models.CharField(max_length=10)),
                ('receiver_unit', models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL, verbose_name='receiver_unit')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
